package com.cy.springcloud.dao;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaseMapper<T> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_admin
     *
     * @mbg.generated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_admin
     *
     * @mbg.generated
     */
    T selectByPrimaryKey(Integer id);

    /**
     * 分页查询-排序-条件
     * @param strWhere
     * @param sort
     * @param offset
     * @param limit
     * @return
     */
    List<T> selectAll(@Param("strWhere") String strWhere, @Param("strCloumn") String strCloumn, @Param("sort") String sort, @Param("offset") Integer offset, @Param("limit") Integer limit);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T record);

    int updateStatusByPrimaryKey(T record);

    int count();

}
